/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AlgoraEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "completeExecution"
      | "createExecution"
      | "developerPercent"
      | "executionCounter"
      | "executions"
      | "owner"
      | "platformFeePercent"
      | "platformWallet"
      | "refundExecution"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateFees"
      | "updatePlatformWallet"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutionCompleted"
      | "ExecutionCreated"
      | "ExecutionRefunded"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "completeExecution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createExecution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "developerPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executionCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundExecution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformWallet",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "completeExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "developerPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformWallet",
    data: BytesLike
  ): Result;
}

export namespace ExecutionCompletedEvent {
  export type InputTuple = [executionId: BigNumberish];
  export type OutputTuple = [executionId: bigint];
  export interface OutputObject {
    executionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionCreatedEvent {
  export type InputTuple = [
    executionId: BigNumberish,
    user: AddressLike,
    developer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    executionId: bigint,
    user: string,
    developer: string,
    amount: bigint
  ];
  export interface OutputObject {
    executionId: bigint;
    user: string;
    developer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionRefundedEvent {
  export type InputTuple = [executionId: BigNumberish];
  export type OutputTuple = [executionId: bigint];
  export interface OutputObject {
    executionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AlgoraEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): AlgoraEscrow;
  waitForDeployment(): Promise<this>;

  interface: AlgoraEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  completeExecution: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  createExecution: TypedContractMethod<
    [developer: AddressLike],
    [bigint],
    "payable"
  >;

  developerPercent: TypedContractMethod<[], [bigint], "view">;

  executionCounter: TypedContractMethod<[], [bigint], "view">;

  executions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        user: string;
        developer: string;
        amount: bigint;
        completed: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  refundExecution: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFees: TypedContractMethod<
    [_platformFee: BigNumberish, _developerSplit: BigNumberish],
    [void],
    "nonpayable"
  >;

  updatePlatformWallet: TypedContractMethod<
    [_newWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "completeExecution"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createExecution"
  ): TypedContractMethod<[developer: AddressLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "developerPercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executionCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        user: string;
        developer: string;
        amount: bigint;
        completed: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundExecution"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFees"
  ): TypedContractMethod<
    [_platformFee: BigNumberish, _developerSplit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePlatformWallet"
  ): TypedContractMethod<[_newWallet: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ExecutionCompleted"
  ): TypedContractEvent<
    ExecutionCompletedEvent.InputTuple,
    ExecutionCompletedEvent.OutputTuple,
    ExecutionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionCreated"
  ): TypedContractEvent<
    ExecutionCreatedEvent.InputTuple,
    ExecutionCreatedEvent.OutputTuple,
    ExecutionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionRefunded"
  ): TypedContractEvent<
    ExecutionRefundedEvent.InputTuple,
    ExecutionRefundedEvent.OutputTuple,
    ExecutionRefundedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ExecutionCompleted(uint256)": TypedContractEvent<
      ExecutionCompletedEvent.InputTuple,
      ExecutionCompletedEvent.OutputTuple,
      ExecutionCompletedEvent.OutputObject
    >;
    ExecutionCompleted: TypedContractEvent<
      ExecutionCompletedEvent.InputTuple,
      ExecutionCompletedEvent.OutputTuple,
      ExecutionCompletedEvent.OutputObject
    >;

    "ExecutionCreated(uint256,address,address,uint256)": TypedContractEvent<
      ExecutionCreatedEvent.InputTuple,
      ExecutionCreatedEvent.OutputTuple,
      ExecutionCreatedEvent.OutputObject
    >;
    ExecutionCreated: TypedContractEvent<
      ExecutionCreatedEvent.InputTuple,
      ExecutionCreatedEvent.OutputTuple,
      ExecutionCreatedEvent.OutputObject
    >;

    "ExecutionRefunded(uint256)": TypedContractEvent<
      ExecutionRefundedEvent.InputTuple,
      ExecutionRefundedEvent.OutputTuple,
      ExecutionRefundedEvent.OutputObject
    >;
    ExecutionRefunded: TypedContractEvent<
      ExecutionRefundedEvent.InputTuple,
      ExecutionRefundedEvent.OutputTuple,
      ExecutionRefundedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
