"use client";

import { motion } from "framer-motion";
import { Play } from "lucide-react";

export function FeaturedAgents() {
  const agents = [
    {
      name: "AI Image Detector",
      description: "Analyze images to determine if they were generated by AI models like Midjourney or DALL-E.",
      price: "0.0005 AVAX",
      tag: "Verification",
    },
    {
      name: "Scam Detector",
      description: "Scan smart contract addresses and websites for known vulnerabilities and rug pull signatures.",
      price: "0.001 AVAX",
      tag: "Security",
    },
    {
      name: "Prompt Optimizer",
      description: "Enhance and refine prompts for LLMs to generate more accurate and structured JSON responses.",
      price: "0.0002 AVAX",
      tag: "Utility",
    },
  ];

  return (
    <section id="features" className="py-24 bg-card relative overflow-hidden text-card-foreground">
      {/* Background decorations */}
      <div className="absolute top-0 right-0 w-1/3 h-[500px] bg-secondary/5 rounded-full blur-[100px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-1/4 h-[400px] bg-primary/5 rounded-full blur-[100px] pointer-events-none" />

      <div className="container mx-auto px-6 relative z-10">
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-6">
          <div className="max-w-2xl">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Featured Agents</h2>
            <p className="text-muted-foreground text-lg">
              Discover powerful AI agents built by the community. Run them instantly with Web3 payments.
            </p>
          </div>
          <button className="text-primary hover:text-[#00eb7b] font-medium flex items-center gap-2 group transition-colors">
            View Marketplace
            <span className="group-hover:translate-x-1 transition-transform">→</span>
          </button>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {agents.map((agent, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              whileHover={{ y: -8 }}
              className="bg-background border border-border rounded-2xl overflow-hidden hover:border-primary/50 transition-all duration-300 hover:shadow-[0_0_30px_rgba(0,255,136,0.15)] flex flex-col h-full group"
            >
              <div className="p-6 flex-1 flex flex-col">
                <div className="mb-4">
                  <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-secondary/10 text-secondary border border-secondary/20 tracking-wider uppercase">
                    {agent.tag}
                  </span>
                </div>
                <h3 className="text-xl font-bold mb-3">{agent.name}</h3>
                <p className="text-muted-foreground mb-6 flex-1 text-sm leading-relaxed">
                  {agent.description}
                </p>
                <div className="flex items-center justify-between pt-6 border-t border-border mt-auto">
                  <div className="flex flex-col">
                     <span className="text-xs text-muted-foreground mb-1">Per Execution</span>
                     <span className="font-mono text-sm font-semibold text-primary">{agent.price}</span>
                  </div>
                  <button className="relative inline-flex items-center justify-center gap-2 px-5 py-2 text-sm font-medium text-foreground bg-white/5 border border-white/10 rounded-full transition-all duration-300 hover:bg-primary hover:text-background hover:border-primary hover:shadow-[0_0_15px_rgba(0,208,112,0.4)] active:scale-95">
                    <Play className="w-4 h-4" fill="currentColor" /> Run
                  </button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
